### ISSUE TITLE
Error when executing XTFA

### ISSUE THREAD

**Issue by sbondorf** [adfeel220/Saihu-TSN-Analysis-Tool-Integration#5]
It may just be due to a missing underscore.
Here's the console output from my system:

```
sbondorf@DNet-MBP-bondorf src % python3 main.py example/demo.json -t XTFA
Receive a JSON file "example/demo.json", converting to an XML ...Done
Analyzing "/Users/sbondorf/Downloads/Saihu-TSN-Analysis-Tool-Integration-main/src/temp/tempnet.xml" using xTFA-TFA...Traceback (most recent call last):
  File "/Users/sbondorf/Downloads/Saihu-TSN-Analysis-Tool-Integration-main/src/main.py", line 115, in <module>
    main()
  File "/Users/sbondorf/Downloads/Saihu-TSN-Analysis-Tool-Integration-main/src/main.py", line 88, in main
    analyzer.analyze_xtfa()
  File "/Users/sbondorf/Downloads/Saihu-TSN-Analysis-Tool-Integration-main/src/saihu/interface.py", line 512, in analyze_xtfa
    xtfa_net.compute()
  File "/Users/sbondorf/Downloads/Saihu-TSN-Analysis-Tool-Integration-main/src/saihu/xtfa/networks.py", line 886, in compute
    return self.cyclicComputation(**kargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sbondorf/Downloads/Saihu-TSN-Analysis-Tool-Integration-main/src/saihu/xtfa/networks.py", line 872, in cyclicComputation
    self.feedForwardComputation()
  File "/Users/sbondorf/Downloads/Saihu-TSN-Analysis-Tool-Integration-main/src/saihu/xtfa/networks.py", line 518, in feedForwardComputation
    newTh.run()
  File "/Users/sbondorf/Downloads/Saihu-TSN-Analysis-Tool-Integration-main/src/saihu/xtfa/networks.py", line 103, in run
    self.computeNode()
  File "/Users/sbondorf/Downloads/Saihu-TSN-Analysis-Tool-Integration-main/src/saihu/xtfa/networks.py", line 73, in computeNode
    self._node.processNode()
  File "/Users/sbondorf/Downloads/Saihu-TSN-Analysis-Tool-Integration-main/src/saihu/xtfa/nodes.py", line 83, in processNode
    self.inputPipeline.processPipeline()
  File "/Users/sbondorf/Downloads/Saihu-TSN-Analysis-Tool-Integration-main/src/saihu/xtfa/inputPipelines.py", line 1426, in processPipeline
    inputPipelineStep.executeStep(self._flowStates, self._partitions)
  File "/Users/sbondorf/Downloads/Saihu-TSN-Analysis-Tool-Integration-main/src/saihu/xtfa/inputPipelines.py", line 477, in executeStep
    if(self.is_packetizer_active):
       ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'InputPortShapingInputPipelineStep' object has no attribute 'is_packetizer_active'. Did you mean: '_is_packetizer_active'?
``

**Comment by LudoInSpace** [comment]
Hey, 
sorry, I recently changed the way the packetizer is modeled in xTFA and you're probably right, I might have forgotten an underscore here.
Will open a MR asap.
